Repository atmtools/arts, pull requests merged in 2019-09, with the labels that each got.

#13 Update doxygen docs in developer guide
  cmake/scripts/update_doxyfile.cmake
  doc/uguide/development.tex
Labels: documentation

#31 Fix out-of-bounds assertion in mspecies
  src/linefunctiondata.cc
Labels: in progress

#44 Fix use of uninitialized member
  src/oem.h
Labels: bug

#43 More doxygen updates, move Faddeeva to 3rdparty
  3rdparty/CMakeLists.txt
  3rdparty/Faddeeva/CMakeLists.txt
  3rdparty/Faddeeva/Faddeeva.cc
  3rdparty/Faddeeva/Faddeeva.hh
  src/CMakeLists.txt
  src/absorption.cc
  src/linefunctions.cc
  src/lineshapes.cc
  src/m_linemixing.cc
  src/m_radiation_field.cc
  src/m_wigner.cc
  src/partial_derivatives.cc
  src/partial_derivatives.h
  src/propmat_field.cc
  src/propmat_field.h
  src/quantum.cc
  src/quantum.h
  src/radiation_field.cc
  src/radiation_field.h
  src/rational.cc
  src/rational.h
  src/test_matpack.cc
  src/test_opt_properties.cc
  src/test_propmat_partials.cc
  src/transmissionmatrix.h
  src/wigner_functions.cc
  src/wigner_functions.h
Labels: documentation

#64 Revision of Jacobian testing
  controlfiles/artscomponents/cia/TestCIADerivs.arts
  controlfiles/artscomponents/lineshapes/TestDoppler.arts
  controlfiles/artscomponents/lineshapes/TestHTP-VP.arts
  controlfiles/artscomponents/lineshapes/TestHTP.arts
  controlfiles/artscomponents/lineshapes/TestHTPLM.arts
  controlfiles/artscomponents/lineshapes/TestLorentz.arts
  controlfiles/artscomponents/lineshapes/TestLorentzLM.arts
  controlfiles/artscomponents/lineshapes/TestSDVP.arts
  controlfiles/artscomponents/lineshapes/TestVoigt.arts
  controlfiles/artscomponents/lineshapes/TestVoigtLM.arts
  controlfiles/artscomponents/nlte/TestPopulationDensityNLTE_lineshape.arts
  controlfiles/artscomponents/radar/TestIyActive_wfuns.arts
  controlfiles/artscomponents/radar/setup_wfun_test.m
  controlfiles/artscomponents/radar/testdata/particle_bulkprop_field.xml
  controlfiles/artscomponents/wfuns/TestWfuns.arts
  controlfiles/artscomponents/wfuns/TestWfunsHybClear.arts
  controlfiles/artscomponents/wfuns/TestWfunsHybCloudy.arts
  controlfiles/artscomponents/zeeman/TestZeeman.arts
  src/m_basic_types.cc
  src/m_cloudradar.cc
  src/m_jacobian.cc
  src/m_retrieval.cc
  src/methods.cc
Labels: in progress
